# Generated by Django 6.0.6 on 2026-07-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('callback', 'Замовити дзвінок'), ('email', 'Написати нам')], default='callback', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка з форми',
                'verbose_name_plural': 'Заявки з форм',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='gallery2',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='gallery1',
        ),
        migrations.DeleteModel(
            name='GeneralSettings',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='info_block1',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='InfoBlock',
        ),
        migrations.DeleteModel(
            name='MainPage',
        ),
    ]
