# Generated by Django 6.0.6 on 2026-07-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Стоматологія «ДіОДі»', max_length=100)),
                ('phone_primary', models.CharField(default='(050) 537-76-57', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, default='(067) 343-60-10', max_length=20)),
                ('email', models.EmailField(default='diodi2001@gmail.com', max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('schedule_weekdays', models.CharField(blank=True, default='9:30 – 21:00', max_length=100)),
                ('schedule_saturday', models.CharField(blank=True, default='за записом', max_length=100)),
                ('schedule_sunday', models.CharField(blank=True, default='вихідний', max_length=100)),
                ('map_embed_url', models.URLField(blank=True, default='https://www.openstreetmap.org/export/embed.html?bbox=24.665%2C48.898%2C24.697%2C48.912&layer=mapnik&marker=48.905185%2C24.680990')),
                ('copyright_text', models.CharField(blank=True, default='© Стоматологія «ДіОДі», Івано-Франківськ', max_length=255)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
