# Generated by Django 6.0.6 on 2026-07-02 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Створено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, upload_to='seo/', verbose_name='OG image за замовчуванням'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='OG description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='seo/', verbose_name='OG image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='OG title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='© Стоматологія «ДіОДі», Івано-Франківськ', max_length=255, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='diodi2001@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, default='https://www.openstreetmap.org/export/embed.html?bbox=24.665%2C48.898%2C24.697%2C48.912&layer=mapnik&marker=48.905185%2C24.680990', verbose_name='URL карти (iframe)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(default='(050) 537-76-57', max_length=20, verbose_name='Телефон (основний)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, default='(067) 343-60-10', max_length=20, verbose_name='Телефон (додатковий)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='schedule_saturday',
            field=models.CharField(blank=True, default='за записом', max_length=100, verbose_name='Графік (Сб)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='schedule_sunday',
            field=models.CharField(blank=True, default='вихідний', max_length=100, verbose_name='Графік (Нд)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='schedule_weekdays',
            field=models.CharField(blank=True, default='9:30 – 21:00', max_length=100, verbose_name='Графік (Пн–Пт)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Стоматологія «ДіОДі»', max_length=100, verbose_name='Назва сайту'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('external', 'Зовнішній ресурс')], max_length=20, verbose_name='Платформа')),
                ('label', models.CharField(max_length=50, verbose_name='Підпис')),
                ('url', models.URLField(verbose_name='Посилання')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.sitesettings', verbose_name='Налаштування сайту')),
            ],
            options={
                'verbose_name': 'Соцмережа',
                'verbose_name_plural': 'Соцмережі',
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
                'indexes': [models.Index(fields=['sort_order'], name='core_social_sort_or_dfbd61_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_settings', 'platform'), name='unique_social_platform_per_site')],
            },
        ),
    ]
