# Generated by Django 6.0.6 on 2026-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_canonical_url_sitesettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='founded_year',
            field=models.PositiveSmallIntegerField(default=2001, help_text='Для статистики «років досвіду» на головній і в «Про клініку».', verbose_name='Рік заснування'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lab_brand_name',
            field=models.CharField(default='Dio-Lab', help_text='Бренд власної зуботехнічної лабораторії (hero / about).', max_length=50, verbose_name='Назва лабораторії'),
        ),
    ]
